import { useState, useEffect } from 'react';

// Using RAWG public API (no key needed for basic endpoints)
// Fallback to mock data if API fails
const RAWG_BASE = 'https://api.rawg.io/api';
const API_KEY = 'f0b8cc3e7f154f0ab1f66b5b39e45a31'; // Free public demo key

const MOCK_GAMES = [
  {
    id: 1,
    name: 'Cyberpunk 2077',
    background_image: 'https://media.rawg.io/media/games/26d/26d4437715bee60138dab4a7c8c59c92.jpg',
    genres: [{ name: 'RPG' }, { name: 'Action' }],
    rating: 4.1,
    released: '2020-12-10',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }],
    price: 59.99,
    discount: 40,
    description: 'An open-world action RPG set in the megalopolis of Night City.',
  },
  {
    id: 2,
    name: 'Elden Ring',
    background_image: 'https://4kwallpapers.com/images/walls/thumbs_3t/7474.jpg',
    genres: [{ name: 'RPG' }, { name: 'Action' }],
    rating: 4.8,
    released: '2022-02-25',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }],
    price: 59.99,
    discount: 10,
    description: 'Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring.',
  },
  {
    id: 3,
    name: 'God of War Ragnarök',
    background_image: 'https://4kwallpapers.com/images/walls/thumbs_3t/8636.jpg',
    genres: [{ name: 'Action' }, { name: 'Adventure' }],
    rating: 4.9,
    released: '2022-11-09',
    platforms: [{ platform: { name: 'PS5' } }],
    price: 69.99,
    discount: 0,
    description: 'Embark on a mythic journey for answers and allies before Ragnarök arrives.',
  },
  {
    id: 4,
    name: 'Red Dead Redemption 2',
    background_image: 'https://wallpapercave.com/wp/wp3770429.png',
    genres: [{ name: 'Action' }, { name: 'Adventure' }],
    rating: 4.7,
    released: '2019-12-05',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'Xbox' } }],
    price: 39.99,
    discount: 60,
    description: "An epic tale of life in America's unforgiving heartland.",
  },
  {
    id: 5,
    name: 'The Witcher 3: Wild Hunt',
    background_image: 'https://media.rawg.io/media/games/618/618c2031a07bbff6b4f611f10b6bcdbc.jpg',
    genres: [{ name: 'RPG' }],
    rating: 4.7,
    released: '2015-05-19',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }],
    price: 29.99,
    discount: 75,
    description: 'A story-driven, open world RPG set in a visually stunning fantasy universe.',
  },
  {
    id: 6,
    name: 'Hades',
    background_image: 'https://images2.alphacoders.com/115/thumbbig-1151800.webp',
    genres: [{ name: 'Action' }, { name: 'Indie' }],
    rating: 4.6,
    released: '2020-09-17',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'Switch' } }],
    price: 24.99,
    discount: 20,
    description: 'Defy the god of the dead as you hack and slash out of the Underworld.',
  },
  {
    id: 7,
    name: 'Minecraft',
    background_image: 'https://media.rawg.io/media/games/b4e/b4e4c73d5aa4ec66bbf75375c4847a2b.jpg',
    genres: [{ name: 'Sandbox' }, { name: 'Survival' }],
    rating: 4.4,
    released: '2011-11-18',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'Mobile' } }],
    price: 26.95,
    discount: 0,
    description: 'Create, explore and survive alone or with friends on mobile devices or Windows 10.',
  },
  {
    id: 8,
    name: 'Hollow Knight',
    background_image: 'https://media.rawg.io/media/games/4cf/4cfc6b7f1850590a4634b08bfab308ab.jpg',
    genres: [{ name: 'Action' }, { name: 'Indie' }],
    rating: 4.6,
    released: '2017-02-24',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'Switch' } }],
    price: 14.99,
    discount: 50,
    description: 'A challenging 2D action-adventure through a vast ruined kingdom of insects and heroes.',
  },
  {
    id: 9,
    name: 'Death Stranding',
    background_image: 'https://images3.alphacoders.com/973/thumbbig-973472.webp',
    genres: [{ name: 'Action' }, { name: 'Adventure' }],
    rating: 4.0,
    released: '2020-07-14',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }],
    price: 39.99,
    discount: 30,
    description: 'As Sam Porter Bridges, traverse a collapsed civilization to reconnect its people.',
  },
  {
    id: 10,
    name: 'Stardew Valley',
    background_image: 'https://media.rawg.io/media/games/713/713269608dc8f2f40f5a670a14b2de94.jpg',
    genres: [{ name: 'Simulation' }, { name: 'Indie' }],
    rating: 4.7,
    released: '2016-02-26',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'Switch' } }],
    price: 14.99,
    discount: 0,
    description: "Build your dream farm. Discover the valley's mysteries.",
  },
  {
    id: 11,
    name: 'Sekiro: Shadows Die Twice',
    background_image: 'https://media.rawg.io/media/games/67f/67f62d1f062a6164f57575e0604ee9f6.jpg',
    genres: [{ name: 'Action' }, { name: 'Adventure' }],
    rating: 4.6,
    released: '2019-03-22',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS4' } }],
    price: 59.99,
    discount: 25,
    description: 'Carve your own path in a brutal, dark depiction of Sengoku Japan.',
  },
  {
    id: 12,
    name: 'Among Us',
    background_image: 'https://4kwallpapers.com/images/walls/thumbs_2t/20157.png',
    genres: [{ name: 'Multiplayer' }, { name: 'Social' }],
    rating: 3.8,
    released: '2018-11-16',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'Mobile' } }],
    price: 4.99,
    discount: 0,
    description: 'Work together to complete tasks—or be the imposter to stop them.',
  },
  {
    id: 13,
    name: 'Fall Guys',
    background_image: 'https://4kwallpapers.com/images/walls/thumbs_2t/5068.jpg',
    genres: [{ name: 'Battle Royale' }, { name: 'Party' }],
    rating: 4.0,
    released: '2020-08-04',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS4' } }],
    price: 19.99,
    discount: 100,
    description: 'Survive chaotic obstacle courses and ridiculous challenges to claim the crown.',
  },
  {
    id: 14,
    name: 'Rocket League',
    background_image: 'https://4kwallpapers.com/images/walls/thumbs_2t/16460.jpg',
    genres: [{ name: 'Sports' }, { name: 'Action' }],
    rating: 4.4,
    released: '2015-07-07',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'Xbox' } }],
    price: 19.99,
    discount: 100,
    description: 'Soccer meets driving in this high-powered hybrid athletic event.',
  },
  {
    id: 15,
    name: 'Apex Legends',
    background_image: 'https://media.rawg.io/media/games/b72/b7233d5d5b1e75e86bb860ccc7aeca85.jpg',
    genres: [{ name: 'Battle Royale' }, { name: 'FPS' }],
    rating: 4.3,
    released: '2019-02-04',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS4' } }],
    price: 0,
    discount: 100,
    description: 'Master an ever-growing roster of diverse legends in this free-to-play battle royale.',
  },
  {
    id: 16,
    name: 'Call of Duty: Warzone 2.0',
    background_image: 'https://images7.alphacoders.com/128/thumbbig-1289348.webp',
    genres: [{ name: 'Battle Royale' }, { name: 'FPS' }],
    rating: 4.2,
    released: '2022-11-16',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }, { platform: { name: 'Xbox Series S/X' } }],
    price: 0,
    discount: 100,
    description: 'Drop into the massive free-to-play battle royale with classic Call of Duty gunplay.',
  },
  {
    id: 17,
    name: 'Fortnite',
    background_image: 'https://media.rawg.io/media/games/46d/46d98e6910fbc0706e2948a7cc9b10c5.jpg',
    genres: [{ name: 'Battle Royale' }, { name: 'Survival' }],
    rating: 4.4,
    released: '2017-07-25',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }, { platform: { name: 'Xbox One' } }, { platform: { name: 'Nintendo Switch' } }],
    price: 0,
    discount: 100,
    description: 'The world\'s biggest battle royale where you can build, fight, and emote your way to victory.',
  },
  {
    id: 18,
    name: 'VALORANT',
    background_image: 'https://4kwallpapers.com/images/walls/thumbs_2t/19112.png',
    genres: [{ name: 'Tactical Shooter' }, { name: 'FPS' }],
    rating: 4.5,
    released: '2020-06-02',
    platforms: [{ platform: { name: 'PC' } }],
    price: 0,
    discount: 100,
    description: 'Precise gunplay meets unique agent abilities in this competitive 5v5 tactical shooter.',
  },
  {
    id: 19,
    name: 'Overwatch 2',
    background_image: 'https://4kwallpapers.com/images/walls/thumbs_2t/18338.jpg',
    genres: [{ name: 'Hero Shooter' }, { name: 'FPS' }],
    rating: 4.1,
    released: '2022-10-04',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }, { platform: { name: 'Xbox Series S/X' } }, { platform: { name: 'Nintendo Switch' } }],
    price: 0,
    discount: 100,
    description: 'Team-based first-person shooter with iconic heroes and fast-paced 5v5 action.',
  },
  {
    id: 20,
    name: 'Counter-Strike 2',
    background_image: 'https://4kwallpapers.com/images/walls/thumbs_2t/11129.png',
    genres: [{ name: 'Tactical Shooter' }, { name: 'FPS' }],
    rating: 4.6,
    released: '2023-09-27',
    platforms: [{ platform: { name: 'PC' } }],
    price: 0,
    discount: 100,
    description: 'The next-generation competitive shooter built on the Source 2 engine.',
  },
  {
    id: 21,
    name: 'Destiny 2',
    background_image: 'https://images4.alphacoders.com/817/thumb-440-817281.webp',
    genres: [{ name: 'MMO' }, { name: 'FPS' }, { name: 'RPG' }],
    rating: 4.0,
    released: '2017-08-28',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }, { platform: { name: 'Xbox Series S/X' } }],
    price: 0,
    discount: 100,
    description: 'An immersive looter-shooter set in a mythic sci-fi universe.',
  },
  {
    id: 22,
    name: 'Warframe',
    background_image: 'https://images.alphacoders.com/516/thumb-440-516341.webp',
    genres: [{ name: 'Action RPG' }, { name: 'Shooter' }],
    rating: 4.4,
    released: '2013-03-25',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }, { platform: { name: 'Xbox One' } }, { platform: { name: 'Nintendo Switch' } }],
    price: 0,
    discount: 100,
    description: 'Ninja space warriors battle across the solar system in this free-to-play action hit.',
  },
  {
    id: 23,
    name: 'Genshin Impact',
    background_image: 'https://4kwallpapers.com/images/walls/thumbs_2t/23044.jpg',
    genres: [{ name: 'Action RPG' }, { name: 'Open World' }],
    rating: 4.7,
    released: '2020-09-28',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }, { platform: { name: 'Mobile' } }],
    price: 0,
    discount: 100,
    description: 'Explore a stunning anime-inspired open world with elemental combat and deep lore.',
  },
  {
    id: 24,
    name: 'DOOM Eternal',
    background_image: 'https://images6.alphacoders.com/981/thumb-440-981724.webp',
    genres: [{ name: 'FPS' }, { name: 'Action' }],
    rating: 4.5,
    released: '2020-03-20',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS4' } }, { platform: { name: 'Xbox One' } }, { platform: { name: 'Nintendo Switch' } }],
    price: 39.99,
    discount: 75,
    description: 'Rip and tear through demon hordes with lightning-fast combat and metal music.',
  },
  {
    id: 25,
    name: 'Resident Evil 4 Remake',
    background_image: 'https://wallpapercave.com/fuwp-510/uwp4999315.jpeg',
    genres: [{ name: 'Survival Horror' }, { name: 'Action' }],
    rating: 4.7,
    released: '2023-03-24',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }, { platform: { name: 'Xbox Series S/X' } }],
    price: 59.99,
    discount: 40,
    description: 'The legendary horror classic returns with modern visuals and refined gameplay.',
  },
  {
    id: 26,
    name: 'Starfield',
    background_image: 'https://images4.alphacoders.com/137/thumb-440-1377541.webp',
    genres: [{ name: 'RPG' }, { name: 'Space' }],
    rating: 4.0,
    released: '2023-09-06',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'Xbox Series S/X' } }],
    price: 69.99,
    discount: 30,
    description: 'Bethesda\'s epic space RPG with over 1,000 planets to explore.',
  },
  {
    id: 27,
    name: 'Hogwarts Legacy',
    background_image: 'https://4kwallpapers.com/images/walls/thumbs_2t/24233.jpg',
    genres: [{ name: 'RPG' }, { name: 'Open World' }],
    rating: 4.3,
    released: '2023-02-10',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }, { platform: { name: 'Xbox Series S/X' } }],
    price: 59.99,
    discount: 50,
    description: 'Live the unwritten story of a student at Hogwarts in the 1800s.',
  },
  {
    id: 28,
    name: 'Baldur\'s Gate 3',
    background_image: 'https://4kwallpapers.com/images/walls/thumbs_2t/12817.jpg',
    genres: [{ name: 'RPG' }, { name: 'Strategy' }],
    rating: 4.9,
    released: '2023-08-03',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }, { platform: { name: 'Xbox Series S/X' } }],
    price: 59.99,
    discount: 20,
    description: 'A deep, choice-driven CRPG set in the Dungeons & Dragons universe.',
  },
  {
    id: 29,
    name: 'Spider-Man: Miles Morales',
    background_image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIRra5x5A3UjZnTcHPxWoXIm9S-GDqTey20Gls_KSeCMRFHgr0&s',
    genres: [{ name: 'Action-Adventure' }, { name: 'Open World' }],
    rating: 4.4,
    released: '2020-11-12',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }, { platform: { name: 'PS4' } }],
    price: 49.99,
    discount: 60,
    description: 'Swing through Marvel\'s New York as the young hero Miles Morales.',
  },
  {
    id: 30,
    name: 'Forza Horizon 5',
    background_image: 'https://4kwallpapers.com/images/walls/thumbs_2t/6668.jpg',
    genres: [{ name: 'Racing' }, { name: 'Open World' }],
    rating: 4.6,
    released: '2021-11-09',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'Xbox Series S/X' } }, { platform: { name: 'Xbox One' } }],
    price: 59.99,
    discount: 50,
    description: 'The ultimate open-world racing game set in vibrant Mexico.',
  },
  {
    id: 31,
    name: 'League of Legends',
    background_image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQT6xypRAHBO2orSVuivqGGEAxRNVQK1w6W8EHfatr9c5x06czDgnYIs9ZyYGeII9Lx27_GhM67zdewiLlsHeaUYJahfxUSh8LQw-hgVw&s=10',
    genres: [{ name: 'MOBA' }, { name: 'Strategy' }],
    rating: 4.2,
    released: '2009-10-27',
    platforms: [{ platform: { name: 'PC' } }],
    price: 0,
    discount: 100,
    description: 'The world\'s most popular MOBA with over 160 champions.',
  },
  {
    id: 32,
    name: 'Dota 2',
    background_image: 'https://media.rawg.io/media/games/095/0953bf01cd4e4dd204aba85489ac9868.jpg',
    genres: [{ name: 'MOBA' }, { name: 'Strategy' }],
    rating: 4.3,
    released: '2013-07-09',
    platforms: [{ platform: { name: 'PC' } }],
    price: 0,
    discount: 100,
    description: 'Deep strategic MOBA with massive esports scene.',
  },
  {
    id: 33,
    name: 'Team Fortress 2',
    background_image: 'https://images4.alphacoders.com/355/thumb-440-35544.webp',
    genres: [{ name: 'Hero Shooter' }, { name: 'FPS' }],
    rating: 4.4,
    released: '2007-10-10',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS3' } }, { platform: { name: 'Xbox 360' } }],
    price: 0,
    discount: 100,
    description: 'Class-based multiplayer mayhem with irreverent humor.',
  },
  {
    id: 34,
    name: 'Path of Exile',
    background_image: 'https://images5.alphacoders.com/547/thumb-440-547295.webp',
    genres: [{ name: 'Action RPG' }, { name: 'MMO' }],
    rating: 4.5,
    released: '2013-10-23',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS4' } }, { platform: { name: 'Xbox One' } }],
    price: 0,
    discount: 100,
    description: 'Dark, deep ARPG with insane character customization.',
  },
  {
    id: 35,
    name: 'Paladins',
    background_image: 'https://images7.alphacoders.com/873/thumb-440-873704.webp',
    genres: [{ name: 'Hero Shooter' }, { name: 'FPS' }],
    rating: 3.9,
    released: '2018-05-08',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS4' } }, { platform: { name: 'Xbox One' } }, { platform: { name: 'Nintendo Switch' } }],
    price: 0,
    discount: 100,
    description: 'Free-to-play fantasy team-based shooter with deep card customization.',
  },
  {
    id: 36,
    name: 'Smite',
    background_image: 'https://images8.alphacoders.com/514/thumb-440-514643.webp',
    genres: [{ name: 'MOBA' }, { name: 'Action' }],
    rating: 4.0,
    released: '2014-03-25',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS4' } }, { platform: { name: 'Xbox One' } }, { platform: { name: 'Nintendo Switch' } }],
    price: 0,
    discount: 100,
    description: 'Third-person MOBA where you control mythological gods.',
  },
  {
    id: 37,
    name: 'War Thunder',
    background_image: 'https://images7.alphacoders.com/584/thumb-440-584609.webp',
    genres: [{ name: 'MMO' }, { name: 'Combat' }],
    rating: 4.1,
    released: '2013-08-15',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }, { platform: { name: 'Xbox Series S/X' } }],
    price: 0,
    discount: 100,
    description: 'Massive online military combat with aircraft, tanks, and ships.',
  },
  {
    id: 38,
    name: 'World of Tanks',
    background_image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRj9PRDy9-cWdQi6uzM2P5NzfnGE6kIxOmSFXIGUcZmsCqCxy0B&s',
    genres: [{ name: 'MMO' }, { name: 'Action' }],
    rating: 4.0,
    released: '2010-08-12',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS4' } }, { platform: { name: 'Xbox One' } }],
    price: 0,
    discount: 100,
    description: 'Team-based tank combat with hundreds of historically inspired vehicles.',
  },
  {
    id: 39,
    name: 'Terraria',
    background_image: 'https://images6.alphacoders.com/606/thumb-440-606046.webp',
    genres: [{ name: 'Sandbox' }, { name: 'Adventure' }],
    rating: 4.6,
    released: '2011-05-16',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'Mobile' } }, { platform: { name: 'Nintendo Switch' } }, { platform: { name: 'PS4' } }],
    price: 9.99,
    discount: 50,
    description: 'Dig, fight, explore, and build in a 2D sandbox adventure.',
  },
  {
    id: 40,
    name: 'Persona 5 Royal',
    background_image: 'https://images.alphacoders.com/137/thumb-440-1370594.webp',
    genres: [{ name: 'RPG' }, { name: 'JRPG' }],
    rating: 4.8,
    released: '2022-10-21',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }, { platform: { name: 'Switch' } }],
    price: 59.99,
    discount: 40,
    description: 'Join the Phantom Thieves and change the world in this acclaimed JRPG.',
  },
  {
    id: 41,
    name: 'Monster Hunter: World',
    background_image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlq4CyR964yzexK-KN1R-joYkQw0LK3BHzmKb_csgdGsHUG74&s',
    genres: [{ name: 'Action RPG' }, { name: 'Hunting' }],
    rating: 4.6,
    released: '2018-01-26',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS4' } }, { platform: { name: 'Xbox One' } }],
    price: 29.99,
    discount: 60,
    description: 'Hunt massive monsters in a living, breathing ecosystem.',
  },
  {
    id: 42,
    name: 'Dark Souls III',
    background_image: 'https://images.alphacoders.com/716/thumb-440-716916.webp',
    genres: [{ name: 'Souls-like' }, { name: 'Action RPG' }],
    rating: 4.7,
    released: '2016-04-12',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS4' } }, { platform: { name: 'Xbox One' } }],
    price: 59.99,
    discount: 75,
    description: 'The legendary dark fantasy epic reaches its climax.',
  },
  {
    id: 43,
    name: 'Nier: Automata',
    background_image: 'https://4kwallpapers.com/images/walls/thumbs_2t/12737.jpg',
    genres: [{ name: 'Action RPG' }, { name: 'Hack and Slash' }],
    rating: 4.7,
    released: '2017-03-17',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS4' } }, { platform: { name: 'Xbox One' } }],
    price: 39.99,
    discount: 50,
    description: 'A masterpiece of action and philosophical storytelling.',
  },
  {
    id: 44,
    name: 'Disco Elysium',
    background_image: 'https://images7.alphacoders.com/119/thumb-440-1193017.webp',
    genres: [{ name: 'RPG' }, { name: 'Detective' }],
    rating: 4.8,
    released: '2019-10-15',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'Switch' } }, { platform: { name: 'PS5' } }],
    price: 39.99,
    discount: 60,
    description: 'Revolutionary open-world RPG with unparalleled dialogue and choices.',
  },
  {
    id: 45,
    name: 'Celeste',
    background_image: 'https://images.alphacoders.com/125/thumb-440-1255538.webp',
    genres: [{ name: 'Platformer' }, { name: 'Indie' }],
    rating: 4.6,
    released: '2018-01-25',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'Switch' } }, { platform: { name: 'PS4' } }],
    price: 19.99,
    discount: 50,
    description: 'A beautiful, challenging platformer about overcoming your inner demons.',
  },
  {
    id: 46,
    name: 'Undertale',
    background_image: 'https://images7.alphacoders.com/798/thumb-440-798682.webp',
    genres: [{ name: 'RPG' }, { name: 'Indie' }],
    rating: 4.7,
    released: '2015-09-15',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'Switch' } }, { platform: { name: 'PS4' } }],
    price: 9.99,
    discount: 40,
    description: 'The RPG where you don\'t have to destroy anyone.',
  },
  {
    id: 47,
    name: 'Outer Wilds',
    background_image: 'https://picfiles.alphacoders.com/195/thumb-1920-195936.jpg',
    genres: [{ name: 'Adventure' }, { name: 'Mystery' }],
    rating: 4.8,
    released: '2019-05-29',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }, { platform: { name: 'Xbox Series S/X' } }],
    price: 24.99,
    discount: 40,
    description: 'An open-world mystery about a solar system trapped in an endless time loop.',
  },
  {
    id: 48,
    name: 'Subnautica',
    background_image: 'https://images5.alphacoders.com/901/thumb-440-901053.webp',
    genres: [{ name: 'Survival' }, { name: 'Adventure' }],
    rating: 4.6,
    released: '2018-01-23',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS4' } }, { platform: { name: 'Xbox One' } }],
    price: 29.99,
    discount: 50,
    description: 'An underwater survival adventure on an alien planet.',
  },
  {
    id: 49,
    name: 'Control',
    background_image: 'https://images.alphacoders.com/103/thumb-440-1037071.webp',
    genres: [{ name: 'Action' }, { name: 'Supernatural' }],
    rating: 4.4,
    released: '2019-08-27',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }, { platform: { name: 'Xbox Series S/X' } }],
    price: 29.99,
    discount: 70,
    description: 'A supernatural action-adventure set in a mysterious New York building.',
  },
  {
    id: 50,
    name: 'Ori and the Will of the Wisps',
    background_image: 'https://picfiles.alphacoders.com/195/thumb-1920-195934.jpg',
    genres: [{ name: 'Platformer' }, { name: 'Metroidvania' }],
    rating: 4.7,
    released: '2020-03-11',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'Xbox Series S/X' } }, { platform: { name: 'Switch' } }],
    price: 29.99,
    discount: 60,
    description: 'A breathtaking action-platformer with emotional storytelling.',
  },
  {
    id: 51,
    name: 'Dead Cells',
    background_image: 'https://media.rawg.io/media/games/be0/be01c3d7d8795a45615da139322ca080.jpg',
    genres: [{ name: 'Roguelike' }, { name: 'Metroidvania' }],
    rating: 4.5,
    released: '2018-08-07',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'Switch' } }, { platform: { name: 'PS4' } }],
    price: 24.99,
    discount: 50,
    description: 'Fast-paced roguelite action with fluid combat and exploration.',
  },
  {
    id: 52,
    name: 'Slay the Spire',
    background_image: 'https://images3.alphacoders.com/136/thumb-440-1362920.webp',
    genres: [{ name: 'Roguelike' }, { name: 'Card Game' }],
    rating: 4.6,
    released: '2019-01-23',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'Switch' } }, { platform: { name: 'Mobile' } }],
    price: 24.99,
    discount: 40,
    description: 'Card-based roguelike that combines deck-building with dungeon crawling.',
  },
  {
    id: 53,
    name: 'Factorio',
    background_image: 'https://images7.alphacoders.com/778/thumb-440-778416.webp',
    genres: [{ name: 'Simulation' }, { name: 'Strategy' }],
    rating: 4.8,
    released: '2020-08-14',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'Switch' } }],
    price: 35.00,
    discount: 0,
    description: 'Build and manage massive factories on an alien planet.',
  },
  {
    id: 54,
    name: 'Satisfactory',
    background_image: 'https://images8.alphacoders.com/120/thumb-440-1205837.webp',
    genres: [{ name: 'Simulation' }, { name: 'Strategy' }],
    rating: 4.6,
    released: '2024-09-10',
    platforms: [{ platform: { name: 'PC' } }],
    price: 39.99,
    discount: 20,
    description: 'First-person factory building game on an alien planet.',
  },
  {
    id: 55,
    name: 'Deep Rock Galactic',
    background_image: 'https://images6.alphacoders.com/120/thumb-440-1204704.webp',
    genres: [{ name: 'FPS' }, { name: 'Co-op' }],
    rating: 4.7,
    released: '2020-05-13',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }, { platform: { name: 'Xbox Series S/X' } }],
    price: 29.99,
    discount: 50,
    description: 'Co-op FPS featuring dwarven space miners fighting alien bugs.',
  },
  {
    id: 56,
    name: 'Risk of Rain 2',
    background_image: 'https://images5.alphacoders.com/120/thumb-440-1202421.webp',
    genres: [{ name: 'Roguelike' }, { name: 'Shooter' }],
    rating: 4.5,
    released: '2020-08-11',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'Switch' } }, { platform: { name: 'PS4' } }],
    price: 24.99,
    discount: 50,
    description: 'Chaotic roguelike third-person shooter with endless replayability.',
  },
  {
    id: 57,
    name: 'Vampire Survivors',
    background_image: 'https://images.alphacoders.com/140/thumb-440-1405710.webp',
    genres: [{ name: 'Roguelike' }, { name: 'Arcade' }],
    rating: 4.5,
    released: '2022-10-20',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'Mobile' } }, { platform: { name: 'Switch' } }],
    price: 4.99,
    discount: 0,
    description: 'Minimalist survival roguelite where you fight hordes of monsters.',
  },
  {
    id: 58,
    name: 'Dave the Diver',
    background_image: 'https://images.alphacoders.com/132/thumb-440-1321419.webp',
    genres: [{ name: 'Adventure' }, { name: 'Simulation' }],
    rating: 4.7,
    released: '2023-06-28',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'Switch' } }],
    price: 19.99,
    discount: 20,
    description: 'Manage a sushi restaurant while exploring the deep sea.',
  },
  {
    id: 59,
    name: 'Cult of the Lamb',
    background_image: 'https://images4.alphacoders.com/123/thumb-440-1236774.webp',
    genres: [{ name: 'Roguelike' }, { name: 'Simulation' }],
    rating: 4.4,
    released: '2022-08-11',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'Switch' } }, { platform: { name: 'PS5' } }],
    price: 24.99,
    discount: 40,
    description: 'Build a cult of woodland creatures in this cute but dark roguelite.',
  },
  {
    id: 60,
    name: 'Stray',
    background_image: 'https://images2.alphacoders.com/125/thumb-440-1258471.webp',
    genres: [{ name: 'Adventure' }, { name: 'Cat Simulator' }],
    rating: 4.5,
    released: '2022-07-19',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }, { platform: { name: 'Xbox Series S/X' } }],
    price: 29.99,
    discount: 40,
    description: 'Play as a stray cat exploring a decaying cybercity.',
  },
  {
    id: 61,
    name: 'Ghost of Tsushima',
    background_image: 'https://images3.alphacoders.com/138/thumb-440-1387219.webp',
    genres: [{ name: 'Action-Adventure' }, { name: 'Open World' }],
    rating: 4.8,
    released: '2020-07-17',
    platforms: [{ platform: { name: 'PS5' } }, { platform: { name: 'PS4' } }],
    price: 59.99,
    discount: 50,
    description: 'Become a samurai in feudal Japan during the Mongol invasion.',
  },
  {
    id: 62,
    name: 'Horizon Forbidden West',
    background_image: 'https://images5.alphacoders.com/114/thumb-440-1148908.webp',
    genres: [{ name: 'Action RPG' }, { name: 'Open World' }],
    rating: 4.6,
    released: '2022-02-18',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }, { platform: { name: 'PS4' } }],
    price: 69.99,
    discount: 40,
    description: 'Aloy ventures into the forbidden west to save the world.',
  },
  {
    id: 63,
    name: 'Final Fantasy VII Remake',
    background_image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXQuNCF-BtXqQPNmltonH4l5W1x40lNvj4GzrL-sOyT8FYoSc&s',
    genres: [{ name: 'RPG' }, { name: 'Action' }],
    rating: 4.6,
    released: '2020-04-10',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }],
    price: 59.99,
    discount: 50,
    description: 'The beloved classic reimagined with modern graphics and gameplay.',
  },
  {
    id: 64,
    name: 'Kingdom Come: Deliverance',
    background_image: 'https://artfiles.alphacoders.com/112/thumb-800-112347.webp',
    genres: [{ name: 'RPG' }, { name: 'Medieval' }],
    rating: 4.2,
    released: '2018-02-13',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS4' } }, { platform: { name: 'Xbox One' } }],
    price: 29.99,
    discount: 70,
    description: 'Realistic medieval RPG set in the Holy Roman Empire.',
  },
  {
    id: 65,
    name: 'Prey (2017)',
    background_image: 'https://picfiles.alphacoders.com/554/thumb-1920-554207.jpg',
    genres: [{ name: 'Immersive Sim' }, { name: 'FPS' }],
    rating: 4.4,
    released: '2017-05-05',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS4' } }, { platform: { name: 'Xbox One' } }],
    price: 29.99,
    discount: 75,
    description: 'First-person sci-fi action game in a space station overrun by aliens.',
  },
  {
    id: 66,
    name: 'Metro Exodus',
    background_image: 'https://images3.alphacoders.com/887/thumb-440-887499.webp',
    genres: [{ name: 'FPS' }, { name: 'Survival' }],
    rating: 4.4,
    released: '2019-02-15',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }, { platform: { name: 'Xbox Series S/X' } }],
    price: 39.99,
    discount: 70,
    description: 'Survival FPS in the post-apocalyptic Russian wilderness.',
  },
  {
    id: 67,
    name: 'Days Gone',
    background_image: 'https://images6.alphacoders.com/140/thumb-440-1406233.webp',
    genres: [{ name: 'Survival Horror' }, { name: 'Open World' }],
    rating: 4.1,
    released: '2019-04-26',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS4' } }, { platform: { name: 'PS5' } }],
    price: 39.99,
    discount: 60,
    description: 'Open-world survival game against massive zombie hordes.',
  },
  {
    id: 68,
    name: 'The Last of Us Part I',
    background_image: 'https://images5.alphacoders.com/394/thumb-440-394511.webp',
    genres: [{ name: 'Action-Adventure' }, { name: 'Survival Horror' }],
    rating: 4.8,
    released: '2022-09-02',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }],
    price: 69.99,
    discount: 30,
    description: 'The complete remake of the PlayStation classic.',
  },
  {
    id: 69,
    name: 'Uncharted 4: A Thief\'s End',
    background_image: 'https://artfiles.alphacoders.com/871/thumb-800-87152.webp',
    genres: [{ name: 'Action-Adventure' }],
    rating: 4.7,
    released: '2016-05-10',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }, { platform: { name: 'PS4' } }],
    price: 39.99,
    discount: 60,
    description: 'Nathan Drake\'s final adventure in this treasure-hunting epic.',
  },
  {
    id: 70,
    name: 'Marvel\'s Spider-Man Remastered',
    background_image: 'https://images6.alphacoders.com/913/thumb-440-913243.webp',
    genres: [{ name: 'Action-Adventure' }, { name: 'Open World' }],
    rating: 4.8,
    released: '2022-08-12',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }],
    price: 59.99,
    discount: 50,
    description: 'Swing through NYC as Spider-Man in this stunning remaster.',
  },
  {
    id: 71,
    name: 'Borderlands 3',
    background_image: 'https://images3.alphacoders.com/101/thumb-440-1012124.webp',
    genres: [{ name: 'FPS' }, { name: 'Looter Shooter' }],
    rating: 4.2,
    released: '2019-09-13',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }, { platform: { name: 'Xbox Series S/X' } }],
    price: 59.99,
    discount: 75,
    description: 'Looter shooter with billions of guns and chaotic humor.',
  },
  {
    id: 72,
    name: 'Far Cry 6',
    background_image: 'https://images.alphacoders.com/115/thumb-440-1151930.webp',
    genres: [{ name: 'FPS' }, { name: 'Open World' }],
    rating: 4.0,
    released: '2021-10-07',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }, { platform: { name: 'Xbox Series S/X' } }],
    price: 59.99,
    discount: 70,
    description: 'Liberate a tropical island from a brutal dictator.',
  },
  {
    id: 73,
    name: 'Assassin\'s Creed Valhalla',
    background_image: 'https://picfiles.alphacoders.com/655/thumb-800-655447.webp',
    genres: [{ name: 'Action RPG' }, { name: 'Open World' }],
    rating: 4.1,
    released: '2020-11-10',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }, { platform: { name: 'Xbox Series S/X' } }],
    price: 59.99,
    discount: 70,
    description: 'Become a Viking raider in Dark Age England.',
  },
  {
    id: 74,
    name: 'Watch Dogs: Legion',
    background_image: 'https://images6.alphacoders.com/108/thumb-440-1087062.webp',
    genres: [{ name: 'Action' }, { name: 'Open World' }],
    rating: 3.9,
    released: '2020-10-29',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }, { platform: { name: 'Xbox Series S/X' } }],
    price: 59.99,
    discount: 80,
    description: 'Recruit anyone in London to fight against oppression.',
  },
  {
    id: 75,
    name: 'Tomb Raider (2013)',
    background_image: 'https://images3.alphacoders.com/736/thumb-440-736906.webp',
    genres: [{ name: 'Action-Adventure' }],
    rating: 4.4,
    released: '2013-03-05',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS4' } }, { platform: { name: 'Xbox One' } }],
    price: 19.99,
    discount: 85,
    description: 'The origin story of Lara Croft, stranded on a mysterious island.',
  },
  {
    id: 76,
    name: 'Rise of the Tomb Raider',
    background_image: 'https://images2.alphacoders.com/597/thumb-440-597950.webp',
    genres: [{ name: 'Action-Adventure' }],
    rating: 4.5,
    released: '2015-11-10',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS4' } }, { platform: { name: 'Xbox One' } }],
    price: 29.99,
    discount: 80,
    description: 'Lara Croft ventures into Siberia to find the secret of immortality.',
  },
  {
    id: 77,
    name: 'Shadow of the Tomb Raider',
    background_image: 'https://picfiles.alphacoders.com/359/thumb-1920-359686.png',
    genres: [{ name: 'Action-Adventure' }],
    rating: 4.3,
    released: '2018-09-14',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS4' } }, { platform: { name: 'Xbox One' } }],
    price: 29.99,
    discount: 80,
    description: 'Lara must save the world from a Mayan apocalypse.',
  },
  {
    id: 78,
    name: 'Dishonored 2',
    background_image: 'https://images8.alphacoders.com/709/thumb-440-709720.webp',
    genres: [{ name: 'Immersive Sim' }, { name: 'Stealth' }],
    rating: 4.4,
    released: '2016-11-11',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS4' } }, { platform: { name: 'Xbox One' } }],
    price: 39.99,
    discount: 75,
    description: 'Play as Emily Kaldwin or Corvo Attano in this stealth masterpiece.',
  },
  {
    id: 79,
    name: 'Deathloop',
    background_image: 'https://images6.alphacoders.com/130/thumb-440-1302897.webp',
    genres: [{ name: 'FPS' }, { name: 'Action' }],
    rating: 4.3,
    released: '2021-09-14',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }, { platform: { name: 'Xbox Series S/X' } }],
    price: 59.99,
    discount: 60,
    description: 'Break the time loop in this stylish FPS from Arkane.',
  },
  {
    id: 80,
    name: 'Returnal',
    background_image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0fiV51jrqjp3kSX3cNgo6gbcShgigpze1R2UIyxkqMQO1luCa0FjzLS2K8GS6ZYS1m0i8I3LMjDgQFWpD0kvpaNUstCWPvQv4FijeMzvf&s=10',
    genres: [{ name: 'Roguelike' }, { name: 'Third-Person Shooter' }],
    rating: 4.5,
    released: '2021-04-30',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }],
    price: 69.99,
    discount: 50,
    description: 'Intense roguelike shooter with psychological horror elements.',
  },
  {
    id: 81,
    name: 'Demon\'s Souls Remake',
    background_image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTx0sXmdyYCKfDcmMfHG2ZdqLsVEhGUv6V0Su9DmC5FsjiXmdentl_4ve411Fz3Wfy0cKwdCe66xRnI4kSF_SbsSttzVZEiLz6LqouPCbwo&s=10',
    genres: [{ name: 'Souls-like' }, { name: 'Action RPG' }],
    rating: 4.7,
    released: '2020-11-12',
    platforms: [{ platform: { name: 'PS5' } }],
    price: 69.99,
    discount: 40,
    description: 'The classic that started the Souls genre, fully remade.',
  },
  {
    id: 82,
    name: 'Bloodborne',
    background_image: 'https://images7.alphacoders.com/610/thumb-440-610261.webp',
    genres: [{ name: 'Souls-like' }, { name: 'Action RPG' }],
    rating: 4.8,
    released: '2015-03-24',
    platforms: [{ platform: { name: 'PS4' } }, { platform: { name: 'PS5' } }],
    price: 39.99,
    discount: 50,
    description: 'Hunt nightmare creatures in a gothic, Lovecraftian city.',
  },
  {
    id: 83,
    name: 'Ratchet & Clank: Rift Apart',
    background_image: 'https://images3.alphacoders.com/115/thumb-440-1151398.webp',
    genres: [{ name: 'Platformer' }, { name: 'Action' }],
    rating: 4.7,
    released: '2021-06-11',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }],
    price: 69.99,
    discount: 40,
    description: 'Dimension-hopping adventure with stunning visuals and gameplay.',
  },
  {
    id: 84,
    name: 'It Takes Two',
    background_image: 'https://images4.alphacoders.com/114/thumb-440-1148443.webp',
    genres: [{ name: 'Co-op' }, { name: 'Adventure' }],
    rating: 4.8,
    released: '2021-03-26',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }, { platform: { name: 'Xbox Series S/X' } }],
    price: 39.99,
    discount: 50,
    description: 'A co-op only adventure about a couple trying to save their relationship.',
  },
  {
    id: 85,
    name: 'A Way Out',
    background_image: 'https://images4.alphacoders.com/887/thumb-440-887514.webp',
    genres: [{ name: 'Co-op' }, { name: 'Adventure' }],
    rating: 4.2,
    released: '2018-03-23',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS4' } }, { platform: { name: 'Xbox One' } }],
    price: 29.99,
    discount: 60,
    description: 'Two prisoners must break out together in this co-op exclusive.',
  },
  {
    id: 86,
    name: 'Portal 2',
    background_image: 'https://images8.alphacoders.com/487/thumb-440-487237.webp',
    genres: [{ name: 'Puzzle' }, { name: 'FPS' }],
    rating: 4.8,
    released: '2011-04-19',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'Switch' } }, { platform: { name: 'PS3' } }],
    price: 9.99,
    discount: 75,
    description: 'The award-winning puzzle-platformer with hilarious writing.',
  },
  {
    id: 87,
    name: 'Half-Life 2',
    background_image: 'https://images.alphacoders.com/365/thumb-440-36561.webp',
    genres: [{ name: 'FPS' }, { name: 'Action' }],
    rating: 4.8,
    released: '2004-11-16',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'Xbox' } }],
    price: 9.99,
    discount: 80,
    description: 'The revolutionary FPS that changed gaming forever.',
  },
  {
    id: 88,
    name: 'BioShock Infinite',
    background_image: 'https://images7.alphacoders.com/482/thumb-440-482944.webp',
    genres: [{ name: 'FPS' }, { name: 'Action' }],
    rating: 4.6,
    released: '2013-03-26',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS4' } }, { platform: { name: 'Xbox One' } }],
    price: 29.99,
    discount: 70,
    description: 'A mind-bending journey through the floating city of Columbia.',
  },
  {
    id: 89,
    name: 'Mass Effect Legendary Edition',
    background_image: 'https://images2.alphacoders.com/115/thumb-440-1150587.webp',
    genres: [{ name: 'RPG' }, { name: 'Action' }],
    rating: 4.8,
    released: '2021-05-14',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }, { platform: { name: 'Xbox Series S/X' } }],
    price: 59.99,
    discount: 60,
    description: 'The complete Mass Effect trilogy remastered in 4K.',
  },
  {
    id: 90,
    name: 'Dragon Age: Inquisition',
    background_image: 'https://images3.alphacoders.com/555/thumb-440-555170.webp',
    genres: [{ name: 'RPG' }, { name: 'Action' }],
    rating: 4.4,
    released: '2014-11-18',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS4' } }, { platform: { name: 'Xbox One' } }],
    price: 39.99,
    discount: 70,
    description: 'Lead the Inquisition to save the world from demonic forces.',
  },
  {
    id: 91,
    name: 'Fallout 4',
    background_image: 'https://images3.alphacoders.com/715/thumb-440-715748.webp',
    genres: [{ name: 'RPG' }, { name: 'Open World' }],
    rating: 4.2,
    released: '2015-11-10',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS4' } }, { platform: { name: 'Xbox One' } }],
    price: 29.99,
    discount: 70,
    description: 'The post-nuclear adventure from Bethesda Game Studios.',
  },
  {
    id: 92,
    name: 'The Elder Scrolls V: Skyrim',
    background_image: 'https://images7.alphacoders.com/319/thumb-440-319944.webp',
    genres: [{ name: 'RPG' }, { name: 'Open World' }],
    rating: 4.8,
    released: '2011-11-11',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }, { platform: { name: 'Xbox Series S/X' } }, { platform: { name: 'Switch' } }],
    price: 39.99,
    discount: 60,
    description: 'The legendary open-world RPG that defined a generation.',
  },
  {
    id: 93,
    name: 'Divinity: Original Sin 2',
    background_image: 'https://images6.alphacoders.com/629/thumb-440-629242.webp',
    genres: [{ name: 'RPG' }, { name: 'Strategy' }],
    rating: 4.8,
    released: '2017-09-14',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'Switch' } }, { platform: { name: 'PS4' } }],
    price: 44.99,
    discount: 60,
    description: 'Deep tactical CRPG with incredible player freedom.',
  },
  {
    id: 94,
    name: 'Pillars of Eternity',
    background_image: 'https://images.alphacoders.com/644/thumb-440-644438.webp',
    genres: [{ name: 'RPG' }, { name: 'Strategy' }],
    rating: 4.3,
    released: '2015-03-26',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'Switch' } }, { platform: { name: 'PS4' } }],
    price: 29.99,
    discount: 70,
    description: 'A spiritual successor to classic CRPGs like Baldur\'s Gate.',
  },
  {
    id: 95,
    name: 'XCOM 2',
    background_image: 'https://images2.alphacoders.com/668/thumb-440-668202.webp',
    genres: [{ name: 'Strategy' }, { name: 'Turn-Based' }],
    rating: 4.5,
    released: '2016-02-05',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS4' } }, { platform: { name: 'Xbox One' } }],
    price: 59.99,
    discount: 75,
    description: 'Lead a resistance force against alien occupation in this tactical classic.',
  },
  {
    id: 96,
    name: 'Civilization VI',
    background_image: 'https://picfiles.alphacoders.com/219/thumb-1920-21949.jpg',
    genres: [{ name: 'Strategy' }, { name: 'Turn-Based' }],
    rating: 4.4,
    released: '2016-10-21',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'Switch' } }, { platform: { name: 'PS4' } }],
    price: 59.99,
    discount: 75,
    description: 'Build your civilization from the stone age to the information age.',
  },
  {
    id: 97,
    name: 'Total War: Warhammer III',
    background_image: 'https://images6.alphacoders.com/121/thumb-440-1212428.webp',
    genres: [{ name: 'Strategy' }, { name: 'Real-Time' }],
    rating: 4.5,
    released: '2022-02-17',
    platforms: [{ platform: { name: 'PC' } }],
    price: 59.99,
    discount: 40,
    description: 'The epic conclusion to the Total War: Warhammer trilogy.',
  },
  {
    id: 98,
    name: 'Age of Empires IV',
    background_image: 'https://4kwallpapers.com/images/walls/thumbs_2t/6868.jpg',
    genres: [{ name: 'Strategy' }, { name: 'Real-Time' }],
    rating: 4.3,
    released: '2021-10-28',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'Xbox Series S/X' } }],
    price: 59.99,
    discount: 50,
    description: 'The return of the legendary RTS franchise.',
  },
  {
    id: 99,
    name: 'Company of Heroes 3',
    background_image: 'https://4kwallpapers.com/images/walls/thumbs_2t/5968.jpg',
    genres: [{ name: 'Strategy' }, { name: 'Real-Time' }],
    rating: 4.1,
    released: '2023-02-23',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'PS5' } }, { platform: { name: 'Xbox Series S/X' } }],
    price: 59.99,
    discount: 30,
    description: 'Deep tactical RTS set in the Mediterranean theater of WWII.',
  },
  {
    id: 100,
    name: 'Halo Infinite',
    background_image: 'https://images.alphacoders.com/102/thumb-440-1020964.webp',
    genres: [{ name: 'FPS' }, { name: 'Action' }],
    rating: 4.3,
    released: '2021-12-08',
    platforms: [{ platform: { name: 'PC' } }, { platform: { name: 'Xbox Series S/X' } }, { platform: { name: 'Xbox One' } }],
    price: 59.99,
    discount: 40,
    description: 'The Master Chief returns in this epic open-world Halo adventure.',
  },
];

export function useGames(params = {}) {
  const [games, setGames] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);

    const fetchGames = async () => {
      try {
        const queryParams = new URLSearchParams({
          key: API_KEY,
          page_size: params.pageSize || 20,
          ordering: params.ordering || '-rating',
          ...params.extra,
        });

        if (params.search) queryParams.set('search', params.search);
        if (params.genres) queryParams.set('genres', params.genres);

        const res = await fetch(`${RAWG_BASE}/games?${queryParams}`, {
          signal: AbortSignal.timeout(5000),
        });

        if (!res.ok) throw new Error('API failed');
        const data = await res.json();

        if (!cancelled) {
          const enriched = data.results.map((g, i) => ({
            ...g,
            price: MOCK_GAMES.find((m) => m.id === g.id)?.price || (9.99 + ((i * 7.5) % 60)).toFixed(2) * 1,
            discount: MOCK_GAMES.find((m) => m.id === g.id)?.discount || [0, 0, 10, 25, 50, 0, 30, 0, 15, 60][i % 10],
          }));
          setGames(enriched);
          setError(null);
        }
      } catch {
        if (!cancelled) {
          let filtered = MOCK_GAMES;
          if (params.search) {
            filtered = filtered.filter((g) =>
              g.name.toLowerCase().includes(params.search.toLowerCase()),
            );
          }
          if (params.excludeWeeklyFree) {
            filtered = filtered.filter((g) => ![101, 102, 103].includes(g.id));
          }
          setGames(filtered);
          setError(null);
        }
      } finally {
        if (!cancelled) setLoading(false);
      }
    };

    fetchGames();
    return () => {
      cancelled = true;
    };
  }, [JSON.stringify(params)]);

  return { games, loading, error };
}

export function useGame(id) {
  const [game, setGame] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!id) return;
    setLoading(true);

    const fetchGame = async () => {
      try {
        const res = await fetch(`${RAWG_BASE}/games/${id}?key=${API_KEY}`, {
          signal: AbortSignal.timeout(5000),
        });
        if (!res.ok) throw new Error('Not found');
        const data = await res.json();
        const mock = MOCK_GAMES.find((m) => m.id === parseInt(id));
        setGame({
          ...data,
          price: mock?.price || 39.99,
          discount: mock?.discount || 0,
        });
      } catch {
        const mock = MOCK_GAMES.find((m) => m.id === parseInt(id));
        setGame(mock || null);
      } finally {
        setLoading(false);
      }
    };

    fetchGame();
  }, [id]);

  return { game, loading };
}

export function useWeeklyFreeGames() {
  return MOCK_GAMES.filter((g) => [30, 12, 4].includes(g.id));
}

export function useFeaturedGames() {
  return MOCK_GAMES.filter((g) => [2, 3, 4].includes(g.id));
}

export { MOCK_GAMES };